sudo: required
services:
  - docker

before_install:
  - docker build -t tkng52/docker-tk -f Dockerfile.dev .

script:
  - docker run tkng52/docker-tk npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-tk"
  env: "DockerTk-env"
  bucket_name: "elasticbeanstalk-us-west-1-906151274306"
  bucket_path: "docker-tk"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
